### ISSUE TITLE
[Suggestion] Build specific versions of strapi and align image tag

### ISSUE THREAD

**Issue by msgeissler** [strapi/strapi-docker#5]
I would like to suggest and talk about the following change (unless that change was already planned anyways):
Once the docker-image and Dockerfile have been proven to be stable (not necessarily strapi itself but the Docker part built around it), it should build specific versions of strapi and tag the image accordingly (e.g. strapi/strapi:v3.0.0-alpha.11).
Right now a user never knows which version of strapi is contained within any given image tag until the image has actually been downloaded and started.

Using environment variables in the Dockerfile it should be possible to use the CI to build, tag and push specific versions of strapi and the image.

**Comment by lucaperret** [comment]
Good proposition. Would you make the PR for this change ?
By the way, can it be more relevant to build the image within the strapi/strapi repository ?
It can integrate a bit more with CI, and trigger the image push on the hub when a tag is processed...

**Comment by msgeissler** [comment]
If I find the time this weekend I will have a look at [automated builds](https://docs.docker.com/docker-hub/builds/), but so far I have no experience with docker hub other than pulling images from there. :)
But from what I have read so far, we should be able to use this repository for that as well.
And it also looks like this is going to be configuration mainly, maybe no big code change is required at all.

From what I can tell, we can keep using the latest strapi version in master and then simply create branches with specific versions of strapi in the Dockerfile. Docker Hub will then automatically grab and built the branch, tag it accordingly (using the branch name) and publish it. Any README.md will automatically be used for the description.

If that is really the case, I will just add another comment with some more description on the process. Please keep in mind that I can only theoretically do this since I do not have the necessary permissions for the git or docker repo to actually do anything. So you might have to test that yourself.

Unless of course you want to build and push the image using your own or a separate CI. Please let me know if that is the case, then I will have to come up with some jenkins configuration for that (so far I have only done that using GitLab CI and pushed to a private registry).

**Comment by msgeissler** [comment]
I created a PR with some minor changes: #7 

To get automated builds by Docker Hub itself [some additional steps are necessary](https://docs.docker.com/docker-hub/builds/):

1. Someone with the Docker Hub login and permissions to the strapi-docker github repo needs [to link the hub account to the strapi/strapi-docker repository](https://docs.docker.com/docker-hub/builds/#link-to-a-hosted-repository-service).
1. [Create an automated build](https://docs.docker.com/docker-hub/builds/#create-an-automated-build) in the Docker Hub settings
    - [Customise the branch name mapping](https://docs.docker.com/docker-cloud/builds/automated-build/#regexes-and-automated-builds) by clicking on **Click here to customize**
        - Match branch `master` to Docker tag `latest`
        - Match tags `/^v?\d+\.\d+\.\d+$/` to `{sourceref}`, these are [releases](https://regex101.com/r/YNRJaK/2)
        - Match tags `/^v?\d+\.\d+\.\d+\-/` to `{sourceref}`, these are [alphas, pre-releases](https://regex101.com/r/hmdP8B/2) etc. (it matches a semver with anything added using a hyphen, sourceref uses the **whole original tag name**, not just any capture group or parts matched by the regex)

The regular expressions are relatively simple. Depending on whether or not you actually want a **v**-prefix they can be adjusted. If you want to make sure they never show up or are always used in the tags you can [use capture groups in the expressions and use those for the Docker tag](https://docs.docker.com/docker-cloud/builds/automated-build/#regexes-and-automated-builds) (something like `/^v?(\d+\.\d+\.\d+)$/` and then in the tag `{\1}` will always exclude the **v**).

That should be enough to get automated builds to work. [This should also use the README.md as the description for the Docker Hub repository](https://docs.docker.com/docker-hub/builds/#understand-the-build-process).

As previously stated, I have not actually gone through the process myself, so there might be some hickups along the way.

PS: Some links, especially those for the regular expressions, refer to the Docker Cloud documentation but should apply to the Docker Hub settings as well. The Docker Hub automated builds documentation lacks nearly all information on the regular expressions.

**Comment by lucaperret** [comment]
Unfortunately we should remove the current image on DockerHub to add the automated builds configuration.
What is your opinion concerning the repository of the Dockerfile? Can it be better to automate build of the strapi image within the official strapi/strapi ?
In this case the image will be build within each strapi release automatically...

**Comment by Aurelsicoko** [comment]
I lost one hour to find a way to edit the current settings and add the automated builds on the current image but it seems this is still a feature request (https://github.com/docker/hub-feedback/issues/450)... Thank a lot @lucaperret for the help though!

**Comment by msgeissler** [comment]
@Aurelsicoko Took me a minute to understand what you meant: You cannot link pre-existing Docker repositories to GitHub repositories.
Would it really be that bad if you deleted the current one and then recreated a Docker repository using the same name but using the automated build option? Right now the amount of stars and pulls on the Docker repo are not that high (since the repo is new) that it would be critical to lose those. I think the feature of automated builds outweighs the need to delete and recreate the Docker repository (but that is just my personal opinion).

@lucaperret It is not unusual to separate them both as you can keep the code separate and reduce the overhead (otherwise everyone will have to checkout the Docker stuff), separate the issues and the PRs. It is also easier to run separate tests since you do not have to merge them with the tests for strapi (or maybe there is another way to separate them). The Dockerfile also needs to be in a sub-folder, otherwise you cannot separate the README files for strapi and the Docker image.
Maybe automating this step using webhooks on releases later on can make it easier but still allows for flexibility and future changes.
Personally, I would prefer separate repositories but I can only give you my opinion on this matter. :)
I guess that depends on the workflow that you use at strapi. Depending on the growth of the code and community, separating it might be easier in the long run?
Plus switching again later on probably means deleting and recreating the Docker Hub repo again, unless they change that in the future. So this decision might be important.

**Comment by lucaperret** [comment]
Thank you @msgeissler. It's also my opinion.
Later on, we should be able to trigger tag on this repository when a Strapi tag is pushed.
Finally @Aurelsicoko you can recreate the DockerHub image with this automated build configuration.

**Comment by Aurelsicoko** [comment]
@lucaperret @msgeissler Guys, both repositories (strapi/strapi and strapi/strapi-docker) are set up with the automated build configuration. Tell me if I need to do something more?

**Comment by msgeissler** [comment]
@Aurelsicoko can you create a tag _3.0.0-alpha.11_ from the current master? _3.0.0-alpha.11_ is the currently used version of strapi in the Dockerfile and the tag should then be picked up by dockerhub and start the first automated build.

**Comment by lucaperret** [comment]
Thank you @Aurelsicoko, why do you have configured two image ?
We should only have one, called `strapi` in my opinion.
Is the automated build force you to use `strapi-docker` as the image name ? (because linked to the github repository)

**Comment by msgeissler** [comment]
The Docker Hub name should be independent of the GitHub repository name.
I just did a quick test and you have to select the repository in a separate page before you can set up the Docker Hub repository name. The Docker Hub name can then still be changed. So I would assume that they are not coupled.

**Comment by Aurelsicoko** [comment]
Sorry guys, I made a mistake. I set up the wrong repository. It's fixed now. The automated build has been set to the `strapi-docker` repository.

**Comment by msgeissler** [comment]
Looks like the README was synced as well, but there seems to be a problem with the HTML at the beginning of it. It doesn't seem to be rendered. But that's for another issue.
Can you test if a GitHub tag works as well? It should show up as a different tag in the Docker Hub as well. If that works as well, we can probably close this issue.

**Comment by lucaperret** [comment]
Fixed by dd46bba4b933dc866fd2680a921b11a03b37814d 
Thanks for the work !

**Comment by lucaperret** [comment]
By the way, there's still have the pulls number to 400+ for the image 👍 
https://hub.docker.com/u/strapi/
Well done.
